name: 'Replace string Action'
description: 'Find and replace a certain string in a text file'
author: 'kramer-e'

inputs:
  android_manifest_paths:
    description: 'The android manifest paths, separated by a ","'
    required: true
  ios_plist_paths:
    description: 'The ios plist paths, separated by a ","'
    required: true
  release_type:
    description: 'The release type "major", "minor" or "patch" to incedment (e.g. "patch": 0.0.1 -> 0.0.2)'
    required: true
  must_match_single_result:
    description: 'When searching path with wildcards ("/**/" or "*.xml") and set "true", requires each given path to have exactly one match.'
    required: true
  sync_all_versions:
    description: 'Retrieves highest version number and semantic version set in all manifest files, increments the values and updates all manifests.
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'arrow-up-circle'
  color: 'green'
