name: Testing manifest version increment

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Incrementing versions
        # use the action that's inside the same repository
        uses: ./
        with:
          android_manifest_paths: './samples/AndroidManifest.xml'
          ios_plist_paths: './samples/Info.plist'
          release_type: 'patch'

      - name: Incrementing versions
        # use the action that's inside the same repository
        uses: ./
        with:
          android_manifest_paths: './**/AndroidManifest.xml'
          ios_plist_paths: './samples/Info.plist'
          release_type: 'patch'
          must_match_single_result: 'false'
          sync_all_versions: 'true'
          
